export const mockMovies = [
  {
    adult: false,
    backdrop_path: '/nLBRD7UPR6GjmWQp6ASAfCTaWKX.jpg',
    id: 502356,
    title: 'The Super Mario Bros. Movie',
    original_language: 'en',
    original_title: 'The Super Mario Bros. Movie',
    overview:
      'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
    poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
    media_type: 'movie',
    genre_ids: [16, 10751, 12, 14, 35],
    popularity: 11392.576,
    release_date: '2023-04-05',
    video: false,
    vote_average: 7.729,
    vote_count: 3161,
  },
  {
    adult: false,
    backdrop_path: '/4t0oBFrJyweYPt0hocW6RUa0b6H.jpg',
    id: 385687,
    title: 'Fast X',
    original_language: 'en',
    original_title: 'Fast X',
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    poster_path: '/1E5baAaEse26fej7uHcjOgEE2t2.jpg',
    media_type: 'movie',
    genre_ids: [28, 80, 53],
    popularity: 7318.346,
    release_date: '2023-05-17',
    video: false,
    vote_average: 6.872,
    vote_count: 308,
  },
  {
    adult: false,
    backdrop_path: '/oblUNeHlwV3VsjB5ITMlco5ZSOF.jpg',
    id: 493529,
    title: 'Dungeons & Dragons: Honor Among Thieves',
    original_language: 'en',
    original_title: 'Dungeons & Dragons: Honor Among Thieves',
    overview:
      'A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.',
    poster_path: '/v7UF7ypAqjsFZFdjksjQ7IUpXdn.jpg',
    media_type: 'movie',
    genre_ids: [12, 14, 35],
    popularity: 1121.915,
    release_date: '2023-03-23',
    video: false,
    vote_average: 7.458,
    vote_count: 1356,
  },
  {
    adult: false,
    backdrop_path: '/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
    id: 447365,
    title: 'Guardians of the Galaxy Vol. 3',
    original_language: 'en',
    original_title: 'Guardians of the Galaxy Vol. 3',
    overview:
      'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.',
    poster_path: '/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
    media_type: 'movie',
    genre_ids: [878, 12, 28],
    popularity: 2296.994,
    release_date: '2023-05-03',
    video: false,
    vote_average: 8.111,
    vote_count: 1458,
  },
  {
    adult: false,
    backdrop_path: '/aAgGrfBwna1nO4M2USxwFgK5O0t.jpg',
    id: 713704,
    title: 'Evil Dead Rise',
    original_language: 'en',
    original_title: 'Evil Dead Rise',
    overview:
      'Three siblings find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.',
    poster_path: '/5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg',
    media_type: 'movie',
    genre_ids: [53, 27, 14],
    popularity: 5196.776,
    release_date: '2023-04-12',
    video: false,
    vote_average: 7.105,
    vote_count: 1231,
  },
  {
    adult: false,
    backdrop_path: '/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg',
    id: 640146,
    title: 'Ant-Man and the Wasp: Quantumania',
    original_language: 'en',
    original_title: 'Ant-Man and the Wasp: Quantumania',
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    poster_path: '/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 878],
    popularity: 4425.387,
    release_date: '2023-02-15',
    video: false,
    vote_average: 6.507,
    vote_count: 2815,
  },
  {
    adult: false,
    backdrop_path: '/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg',
    id: 640146,
    title: 'Ant-Man and the Wasp: Quantumania',
    original_language: 'en',
    original_title: 'Ant-Man and the Wasp: Quantumania',
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    poster_path: '/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 878],
    popularity: 4425.387,
    release_date: '2023-02-15',
    video: false,
    vote_average: 6.507,
    vote_count: 2815,
  },
  {
    adult: false,
    backdrop_path: '/i1eghEBiC0gN4KnwuUGC2fNiX1f.jpg',
    id: 552688,
    title: 'The Mother',
    original_language: 'en',
    original_title: 'The Mother',
    overview:
      'A deadly female assassin comes out of hiding to protect the daughter that she gave up years before, while on the run from dangerous men.',
    poster_path: '/vnRthEZz16Q9VWcP5homkHxyHoy.jpg',
    media_type: 'movie',
    genre_ids: [28, 53],
    popularity: 2093.491,
    release_date: '2023-05-04',
    video: false,
    vote_average: 6.746,
    vote_count: 487,
  },
  {
    adult: false,
    backdrop_path: '/aT3sRVqgpkyCo23fp9myVfKPWbA.jpg',
    id: 964980,
    title: 'Air',
    original_language: 'en',
    original_title: 'Air',
    overview:
      "Discover the game-changing partnership between a then undiscovered Michael Jordan and Nike's fledgling basketball division which revolutionized the world of sports and culture with the Air Jordan brand.",
    poster_path: '/76AKQPdH3M8cvsFR9K8JsOzVlY5.jpg',
    media_type: 'movie',
    genre_ids: [18, 36],
    popularity: 672.415,
    release_date: '2023-04-05',
    video: false,
    vote_average: 7.468,
    vote_count: 701,
  },
  {
    adult: false,
    backdrop_path: '/94TIUEhuwv8PhdIADEvSuwPljS5.jpg',
    id: 840326,
    title: 'Sisu',
    original_language: 'fi',
    original_title: 'Sisu',
    overview:
      'Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.',
    poster_path: '/tELs0h3PPicRbsuu5cQ8UFcBQno.jpg',
    media_type: 'movie',
    genre_ids: [28, 10752],
    popularity: 2634.212,
    release_date: '2023-01-27',
    video: false,
    vote_average: 7.382,
    vote_count: 263,
  },
  {
    adult: false,
    backdrop_path: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
    id: 603692,
    title: 'John Wick: Chapter 4',
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    media_type: 'movie',
    genre_ids: [28, 53, 80],
    popularity: 1602.399,
    release_date: '2023-03-22',
    video: false,
    vote_average: 7.9,
    vote_count: 1452,
  },
  {
    adult: false,
    backdrop_path: '/i1eghEBiC0gN4KnwuUGC2fNiX1f.jpg',
    id: 552688,
    title: 'The Mother',
    original_language: 'en',
    original_title: 'The Mother',
    overview:
      'A deadly female assassin comes out of hiding to protect the daughter that she gave up years before, while on the run from dangerous men.',
    poster_path: '/vnRthEZz16Q9VWcP5homkHxyHoy.jpg',
    media_type: 'movie',
    genre_ids: [28, 53],
    popularity: 2093.491,
    release_date: '2023-05-04',
    video: false,
    vote_average: 6.746,
    vote_count: 487,
  },
  {
    adult: false,
    backdrop_path: '/aT3sRVqgpkyCo23fp9myVfKPWbA.jpg',
    id: 964980,
    title: 'Air',
    original_language: 'en',
    original_title: 'Air',
    overview:
      "Discover the game-changing partnership between a then undiscovered Michael Jordan and Nike's fledgling basketball division which revolutionized the world of sports and culture with the Air Jordan brand.",
    poster_path: '/76AKQPdH3M8cvsFR9K8JsOzVlY5.jpg',
    media_type: 'movie',
    genre_ids: [18, 36],
    popularity: 672.415,
    release_date: '2023-04-05',
    video: false,
    vote_average: 7.468,
    vote_count: 701,
  },
  {
    adult: false,
    backdrop_path: '/94TIUEhuwv8PhdIADEvSuwPljS5.jpg',
    id: 840326,
    title: 'Sisu',
    original_language: 'fi',
    original_title: 'Sisu',
    overview:
      'Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.',
    poster_path: '/tELs0h3PPicRbsuu5cQ8UFcBQno.jpg',
    media_type: 'movie',
    genre_ids: [28, 10752],
    popularity: 2634.212,
    release_date: '2023-01-27',
    video: false,
    vote_average: 7.382,
    vote_count: 263,
  },
  {
    adult: false,
    backdrop_path: '/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg',
    id: 640146,
    title: 'Ant-Man and the Wasp: Quantumania',
    original_language: 'en',
    original_title: 'Ant-Man and the Wasp: Quantumania',
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    poster_path: '/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 878],
    popularity: 4425.387,
    release_date: '2023-02-15',
    video: false,
    vote_average: 6.507,
    vote_count: 2815,
  },
  {
    adult: false,
    backdrop_path: '/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg',
    id: 640146,
    title: 'Ant-Man and the Wasp: Quantumania',
    original_language: 'en',
    original_title: 'Ant-Man and the Wasp: Quantumania',
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    poster_path: '/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 878],
    popularity: 4425.387,
    release_date: '2023-02-15',
    video: false,
    vote_average: 6.507,
    vote_count: 2815,
  },
  {
    adult: false,
    backdrop_path: '/i1eghEBiC0gN4KnwuUGC2fNiX1f.jpg',
    id: 552688,
    title: 'The Mother',
    original_language: 'en',
    original_title: 'The Mother',
    overview:
      'A deadly female assassin comes out of hiding to protect the daughter that she gave up years before, while on the run from dangerous men.',
    poster_path: '/vnRthEZz16Q9VWcP5homkHxyHoy.jpg',
    media_type: 'movie',
    genre_ids: [28, 53],
    popularity: 2093.491,
    release_date: '2023-05-04',
    video: false,
    vote_average: 6.746,
    vote_count: 487,
  },
  {
    adult: false,
    backdrop_path: '/aT3sRVqgpkyCo23fp9myVfKPWbA.jpg',
    id: 964980,
    title: 'Air',
    original_language: 'en',
    original_title: 'Air',
    overview:
      "Discover the game-changing partnership between a then undiscovered Michael Jordan and Nike's fledgling basketball division which revolutionized the world of sports and culture with the Air Jordan brand.",
    poster_path: '/76AKQPdH3M8cvsFR9K8JsOzVlY5.jpg',
    media_type: 'movie',
    genre_ids: [18, 36],
    popularity: 672.415,
    release_date: '2023-04-05',
    video: false,
    vote_average: 7.468,
    vote_count: 701,
  },
  {
    adult: false,
    backdrop_path: '/94TIUEhuwv8PhdIADEvSuwPljS5.jpg',
    id: 840326,
    title: 'Sisu',
    original_language: 'fi',
    original_title: 'Sisu',
    overview:
      'Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.',
    poster_path: '/tELs0h3PPicRbsuu5cQ8UFcBQno.jpg',
    media_type: 'movie',
    genre_ids: [28, 10752],
    popularity: 2634.212,
    release_date: '2023-01-27',
    video: false,
    vote_average: 7.382,
    vote_count: 263,
  },
  {
    adult: false,
    backdrop_path: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
    id: 603692,
    title: 'John Wick: Chapter 4',
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    media_type: 'movie',
    genre_ids: [28, 53, 80],
    popularity: 1602.399,
    release_date: '2023-03-22',
    video: false,
    vote_average: 7.9,
    vote_count: 1452,
  },
  {
    adult: false,
    backdrop_path: '/i1eghEBiC0gN4KnwuUGC2fNiX1f.jpg',
    id: 552688,
    title: 'The Mother',
    original_language: 'en',
    original_title: 'The Mother',
    overview:
      'A deadly female assassin comes out of hiding to protect the daughter that she gave up years before, while on the run from dangerous men.',
    poster_path: '/vnRthEZz16Q9VWcP5homkHxyHoy.jpg',
    media_type: 'movie',
    genre_ids: [28, 53],
    popularity: 2093.491,
    release_date: '2023-05-04',
    video: false,
    vote_average: 6.746,
    vote_count: 487,
  },
  {
    adult: false,
    backdrop_path: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
    id: 603692,
    title: 'John Wick: Chapter 4',
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    media_type: 'movie',
    genre_ids: [28, 53, 80],
    popularity: 1602.399,
    release_date: '2023-03-22',
    video: false,
    vote_average: 7.9,
    vote_count: 1452,
  },
  {
    adult: false,
    backdrop_path: '/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg',
    id: 758323,
    title: "The Pope's Exorcist",
    original_language: 'en',
    original_title: "The Pope's Exorcist",
    overview:
      "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
    poster_path: '/4IjRR2OW2itjQWQnmlUzvwLz9DQ.jpg',
    media_type: 'movie',
    genre_ids: [27, 53, 14],
    popularity: 2842.266,
    release_date: '2023-04-05',
    video: false,
    vote_average: 7.251,
    vote_count: 1112,
  },
  {
    adult: false,
    backdrop_path: '/eTvN54pd83TrSEOz6wbsXEJktCV.jpg',
    id: 882569,
    title: "Guy Ritchie's The Covenant",
    original_language: 'en',
    original_title: "Guy Ritchie's The Covenant",
    overview:
      'During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.',
    poster_path: '/aX0H63vho7rZ9Rm3I567Zf00Z1t.jpg',
    media_type: 'movie',
    genre_ids: [10752, 28, 53],
    popularity: 3167.399,
    release_date: '2023-04-19',
    video: false,
    vote_average: 7.651,
    vote_count: 284,
  },
  {
    adult: false,
    backdrop_path: '/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg',
    id: 640146,
    title: 'Ant-Man and the Wasp: Quantumania',
    original_language: 'en',
    original_title: 'Ant-Man and the Wasp: Quantumania',
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    poster_path: '/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 878],
    popularity: 4425.387,
    release_date: '2023-02-15',
    video: false,
    vote_average: 6.507,
    vote_count: 2815,
  },
  {
    adult: false,
    backdrop_path: '/i1eghEBiC0gN4KnwuUGC2fNiX1f.jpg',
    id: 552688,
    title: 'The Mother',
    original_language: 'en',
    original_title: 'The Mother',
    overview:
      'A deadly female assassin comes out of hiding to protect the daughter that she gave up years before, while on the run from dangerous men.',
    poster_path: '/vnRthEZz16Q9VWcP5homkHxyHoy.jpg',
    media_type: 'movie',
    genre_ids: [28, 53],
    popularity: 2093.491,
    release_date: '2023-05-04',
    video: false,
    vote_average: 6.746,
    vote_count: 487,
  },
  {
    adult: false,
    backdrop_path: '/aT3sRVqgpkyCo23fp9myVfKPWbA.jpg',
    id: 964980,
    title: 'Air',
    original_language: 'en',
    original_title: 'Air',
    overview:
      "Discover the game-changing partnership between a then undiscovered Michael Jordan and Nike's fledgling basketball division which revolutionized the world of sports and culture with the Air Jordan brand.",
    poster_path: '/76AKQPdH3M8cvsFR9K8JsOzVlY5.jpg',
    media_type: 'movie',
    genre_ids: [18, 36],
    popularity: 672.415,
    release_date: '2023-04-05',
    video: false,
    vote_average: 7.468,
    vote_count: 701,
  },
  {
    adult: false,
    backdrop_path: '/94TIUEhuwv8PhdIADEvSuwPljS5.jpg',
    id: 840326,
    title: 'Sisu',
    original_language: 'fi',
    original_title: 'Sisu',
    overview:
      'Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.',
    poster_path: '/tELs0h3PPicRbsuu5cQ8UFcBQno.jpg',
    media_type: 'movie',
    genre_ids: [28, 10752],
    popularity: 2634.212,
    release_date: '2023-01-27',
    video: false,
    vote_average: 7.382,
    vote_count: 263,
  },
  {
    adult: false,
    backdrop_path: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
    id: 603692,
    title: 'John Wick: Chapter 4',
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    media_type: 'movie',
    genre_ids: [28, 53, 80],
    popularity: 1602.399,
    release_date: '2023-03-22',
    video: false,
    vote_average: 7.9,
    vote_count: 1452,
  },
  {
    adult: false,
    backdrop_path: '/94TIUEhuwv8PhdIADEvSuwPljS5.jpg',
    id: 840326,
    title: 'Sisu',
    original_language: 'fi',
    original_title: 'Sisu',
    overview:
      'Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.',
    poster_path: '/tELs0h3PPicRbsuu5cQ8UFcBQno.jpg',
    media_type: 'movie',
    genre_ids: [28, 10752],
    popularity: 2634.212,
    release_date: '2023-01-27',
    video: false,
    vote_average: 7.382,
    vote_count: 263,
  },
  {
    adult: false,
    backdrop_path: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
    id: 603692,
    title: 'John Wick: Chapter 4',
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    media_type: 'movie',
    genre_ids: [28, 53, 80],
    popularity: 1602.399,
    release_date: '2023-03-22',
    video: false,
    vote_average: 7.9,
    vote_count: 1452,
  },
  {
    adult: false,
    backdrop_path: '/i1eghEBiC0gN4KnwuUGC2fNiX1f.jpg',
    id: 552688,
    title: 'The Mother',
    original_language: 'en',
    original_title: 'The Mother',
    overview:
      'A deadly female assassin comes out of hiding to protect the daughter that she gave up years before, while on the run from dangerous men.',
    poster_path: '/vnRthEZz16Q9VWcP5homkHxyHoy.jpg',
    media_type: 'movie',
    genre_ids: [28, 53],
    popularity: 2093.491,
    release_date: '2023-05-04',
    video: false,
    vote_average: 6.746,
    vote_count: 487,
  },
  {
    adult: false,
    backdrop_path: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
    id: 603692,
    title: 'John Wick: Chapter 4',
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    media_type: 'movie',
    genre_ids: [28, 53, 80],
    popularity: 1602.399,
    release_date: '2023-03-22',
    video: false,
    vote_average: 7.9,
    vote_count: 1452,
  },
  {
    adult: false,
    backdrop_path: '/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg',
    id: 758323,
    title: "The Pope's Exorcist",
    original_language: 'en',
    original_title: "The Pope's Exorcist",
    overview:
      "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
    poster_path: '/4IjRR2OW2itjQWQnmlUzvwLz9DQ.jpg',
    media_type: 'movie',
    genre_ids: [27, 53, 14],
    popularity: 2842.266,
    release_date: '2023-04-05',
    video: false,
    vote_average: 7.251,
    vote_count: 1112,
  },
  {
    adult: false,
    backdrop_path: '/eTvN54pd83TrSEOz6wbsXEJktCV.jpg',
    id: 882569,
    title: "Guy Ritchie's The Covenant",
    original_language: 'en',
    original_title: "Guy Ritchie's The Covenant",
    overview:
      'During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.',
    poster_path: '/aX0H63vho7rZ9Rm3I567Zf00Z1t.jpg',
    media_type: 'movie',
    genre_ids: [10752, 28, 53],
    popularity: 3167.399,
    release_date: '2023-04-19',
    video: false,
    vote_average: 7.651,
    vote_count: 284,
  },
  {
    adult: false,
    backdrop_path: '/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg',
    id: 640146,
    title: 'Ant-Man and the Wasp: Quantumania',
    original_language: 'en',
    original_title: 'Ant-Man and the Wasp: Quantumania',
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    poster_path: '/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 878],
    popularity: 4425.387,
    release_date: '2023-02-15',
    video: false,
    vote_average: 6.507,
    vote_count: 2815,
  },
  {
    adult: false,
    backdrop_path: '/i1eghEBiC0gN4KnwuUGC2fNiX1f.jpg',
    id: 552688,
    title: 'The Mother',
    original_language: 'en',
    original_title: 'The Mother',
    overview:
      'A deadly female assassin comes out of hiding to protect the daughter that she gave up years before, while on the run from dangerous men.',
    poster_path: '/vnRthEZz16Q9VWcP5homkHxyHoy.jpg',
    media_type: 'movie',
    genre_ids: [28, 53],
    popularity: 2093.491,
    release_date: '2023-05-04',
    video: false,
    vote_average: 6.746,
    vote_count: 487,
  },
  {
    adult: false,
    backdrop_path: '/aT3sRVqgpkyCo23fp9myVfKPWbA.jpg',
    id: 964980,
    title: 'Air',
    original_language: 'en',
    original_title: 'Air',
    overview:
      "Discover the game-changing partnership between a then undiscovered Michael Jordan and Nike's fledgling basketball division which revolutionized the world of sports and culture with the Air Jordan brand.",
    poster_path: '/76AKQPdH3M8cvsFR9K8JsOzVlY5.jpg',
    media_type: 'movie',
    genre_ids: [18, 36],
    popularity: 672.415,
    release_date: '2023-04-05',
    video: false,
    vote_average: 7.468,
    vote_count: 701,
  },
  {
    adult: false,
    backdrop_path: '/94TIUEhuwv8PhdIADEvSuwPljS5.jpg',
    id: 840326,
    title: 'Sisu',
    original_language: 'fi',
    original_title: 'Sisu',
    overview:
      'Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.',
    poster_path: '/tELs0h3PPicRbsuu5cQ8UFcBQno.jpg',
    media_type: 'movie',
    genre_ids: [28, 10752],
    popularity: 2634.212,
    release_date: '2023-01-27',
    video: false,
    vote_average: 7.382,
    vote_count: 263,
  },
  {
    adult: false,
    backdrop_path: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
    id: 603692,
    title: 'John Wick: Chapter 4',
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    media_type: 'movie',
    genre_ids: [28, 53, 80],
    popularity: 1602.399,
    release_date: '2023-03-22',
    video: false,
    vote_average: 7.9,
    vote_count: 1452,
  },
  {
    adult: false,
    backdrop_path: '/mfPfFVhpnGp8bG4IUoBJPUs2xKj.jpg',
    id: 620705,
    title: 'Crater',
    original_language: 'en',
    original_title: 'Crater',
    overview:
      'After the death of his father, a boy growing up on a lunar mining colony takes a trip to explore a legendary crater, along with his four best friends, prior to being permanently relocated to another planet.',
    poster_path: '/n8ZpMwYT02XjpQHpSxn1eJw5Zpz.jpg',
    media_type: 'movie',
    genre_ids: [878, 28, 12, 10751],
    popularity: 1257.589,
    release_date: '2023-05-12',
    video: false,
    vote_average: 6.667,
    vote_count: 93,
  },
  {
    adult: false,
    backdrop_path: '/8rpDcsfLJypbO6vREc0547VKqEv.jpg',
    id: 76600,
    title: 'Avatar: The Way of Water',
    original_language: 'en',
    original_title: 'Avatar: The Way of Water',
    overview:
      'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    media_type: 'movie',
    genre_ids: [878, 12, 28],
    popularity: 2206.792,
    release_date: '2022-12-14',
    video: false,
    vote_average: 7.701,
    vote_count: 8114,
  },
];
const organizeArray = array => {
  let object = {};
  let totalPages = Math.ceil(array.length / 20);
  for (let i = 0; i < totalPages; i++) {
    object[i + 1] = array.slice(i * 20, i * 20 + 20);
  }
  object.total_pages = totalPages;
  return object;
};
